export const TODO_ITEMS_SAVE = 'TODO_ITEMS_SAVE';
export const TODO_ITEM_ADD = 'TODO_ITEM_ADD';
export const TODO_ITEM_REMOVE = 'TODO_ITEM_REMOVE';
export const TODO_ITEM_SET_CHECKED = 'TODO_ITEM_SET_CHECKED';

export const TODO_LISTS_SAVE = 'TODO_LISTS_SAVE';
export const TODO_LIST_ADD = 'TODO_LIST_ADD';
export const TODO_LIST_REMOVE = 'TODO_LIST_REMOVE';
export const TODO_LIST_SELECT = 'TODO_LIST_SELECT';

export const TODO_GROUPS_SAVE = 'TODO_GROUPS_SAVE';
export const TODO_GROUP_ADD = 'TODO_GROUP_ADD';
export const TODO_GROUP_REMOVE = 'TODO_GROUP_REMOVE';
export const TODO_GROUP_SELECT = 'TODO_GROUP_SELECT';
